
exports.seed = function(knex, Promise) {
  return knex('book').del().then(function(){
    return Promise.all([
      knex('book').insert({
        title: 'The Three-Body Problem',
        winner: '{"Hugo"}',
        year: '2015',
        author_first: 'Cixin',
        author_last: 'Liu',
        publisher: 'Tor Books',
      }),
      knex('book').insert({
        title: 'Ancillary Justice',
        winner: '{"Hugo", "Nebula"}',
        year: '2014',
        author_first: 'Ann',
        author_last: 'Leckie',
        publisher: 'Orbit Books',
      }),
      knex('book').insert({
        title: 'Redshirts',
        winner: '{"Hugo", "Locus"}',
        year: '2013',
        author_first: 'John',
        author_last: 'Scalzi',
        publisher: 'Tor Books',
      }),
      knex('book').insert({
        title: 'Among Others',
        winner: '{"Hugo", "Nebula"}',
        year: '2012',
        author_first: 'Jo',
        author_last: 'Walton',
        publisher: 'Tor Books',
      }),
      knex('book').insert({
        title: 'All Clear',
        winner: '{"Hugo", "Nebula", "Locus"}',
        year: '2011',
        author_first: 'Connie',
        author_last: 'Willis',
        publisher: 'Spectra Books',
      }),
      knex('book').insert({
        title: 'Blackout',
        winner: '{"Hugo", "Nebula", "Locus"}',
        year: '2011',
        author_first: 'Connie',
        author_last: 'Willis',
        publisher: 'Spectra Books',
      }),
      knex('book').insert({
        title: 'The Windup Girl',
        winner: '{"Hugo", "Nebula"}',
        year: '2010',
        author_first: 'Paolo',
        author_last: 'Bacigalupi',
        publisher: 'Night Shade Books',
      }),
      knex('book').insert({
        title: 'The City & The City',
        winner: '{"Hugo"}',
        year: '2010',
        author_first: 'China',
        author_last: 'Mi'+String.fromCharCode(233)+'ville',
        publisher: 'Del Rey Books',
      }),
      knex('book').insert({
        title: 'The Graveyard Book',
        winner: '{"Hugo"}',
        year: '2009',
        author_first: 'Neil',
        author_last: 'Gaiman',
        publisher: 'HarperCollins',
      }),
      knex('book').insert({
        title: 'The Yiddish Policemen\'s Union',
        winner: '{"Hugo", "Nebula", "Locus"}',
        year: '2008',
        author_first: 'Michael',
        author_last: 'Chabon',
        publisher: 'HarperCollins',
      }),
      knex('book').insert({
        title: 'Rainbows End',
        winner: '{"Hugo", "Locus"}',
        year: '2007',
        author_first: 'Vernor',
        author_last: 'Vinge',
        publisher: 'Tor Books',
      }),
      knex('book').insert({
        title: 'Spin',
        winner: '{"Hugo"}',
        year: '2006',
        author_first: 'Robert Charles',
        author_last: 'Wilson',
        publisher: 'Tor Books',
      }),
      knex('book').insert({
        title: 'Annihilation',
        winner: '{"Nebula"}',
        year: '2015',
        author_first: 'Jeff',
        author_last: 'VanderMeer',
        publisher: 'Farrar, Straus, and Giroux',
      }),
      knex('book').insert({
        title: '2312',
        winner: '{"Nebula"}',
        year: '2013',
        author_first: 'Kim Stanley',
        author_last: 'Robinson',
        publisher: 'Orbit Books',
      }),
      knex('book').insert({
        title: 'Powers',
        winner: '{"Nebula"}',
        year: '2009',
        author_first: 'Ursula K.',
        author_last: 'Le Guin',
        publisher: 'Harcourt',
      }),
      knex('book').insert({
        title: 'Seeker',
        winner: '{"Nebula"}',
        year: '2007',
        author_first: 'Jack',
        author_last: 'McDevitt',
        publisher: 'Ace Books',
      }),
      knex('book').insert({
        title: 'Camouflage',
        winner: '{"Nebula"}',
        year: '2006',
        author_first: 'Joe',
        author_last: 'Haldeman',
        publisher: 'Analog Science Fiction and Fact',
      }),
      knex('book').insert({
        title: 'Influx',
        winner: '{"Prometheus"}',
        year: '2015',
        author_first: 'Daniel',
        author_last: 'Suarez',
        publisher: 'Dutton',
      }),
      knex('book').insert({
        title: 'Nexus',
        winner: '{"Prometheus"}',
        year: '2014',
        author_first: 'Ramez',
        author_last: 'Naam',
        publisher: 'Angry Robot',
      }),
      knex('book').insert({
        title: 'Homeland',
        winner: '{"Prometheus"}',
        year: '2014',
        author_first: 'Cory',
        author_last: 'Doctorow',
        publisher: 'Tor Books',
      }),
      knex('book').insert({
        title: 'Pirate Cinema',
        winner: '{"Prometheus"}',
        year: '2013',
        author_first: 'Cory',
        author_last: 'Doctorow',
        publisher: 'Tor Books',
      }),
      knex('book').insert({
        title: 'The Freedom Maze',
        winner: '{"Prometheus"}',
        year: '2012',
        author_first: 'Delia',
        author_last: 'Sherman',
        publisher: 'Big Mouth House',
      }),
      knex('book').insert({
        title: 'Ready Player One',
        winner: '{"Prometheus"}',
        year: '2012',
        author_first: 'Ernest',
        author_last: 'Cline',
        publisher: 'Random House',
      }),
      knex('book').insert({
        title: 'Darkship Thieves',
        winner: '{"Prometheus"}',
        year: '2011',
        author_first: 'Sarah A.',
        author_last: 'Hoyt',
        publisher: 'Baen Books',
      }),
      knex('book').insert({
        title: 'The Unincorporated Man',
        winner: '{"Prometheus"}',
        year: '2010',
        author_first: 'Dani & Eytan',
        author_last: 'Kollin',
        publisher: 'Tor Books',
      }),
      knex('book').insert({
        title: 'Little Brother',
        winner: '{"Prometheus"}',
        year: '2009',
        author_first: 'Cory',
        author_last: 'Doctorow',
        publisher: 'Tor Books',
      }),
      knex('book').insert({
        title: 'Ha\'penny',
        winner: '{"Prometheus"}',
        year: '2008',
        author_first: 'Jo',
        author_last: 'Walton',
        publisher: 'Tor Books',
      }),

      knex('book').insert({
        title: 'The Gladiator',
        winner: '{"Prometheus"}',
        year: '2008',
        author_first: 'Harry',
        author_last: 'Turtledove',
        publisher: 'Tor Books',
      }),
      knex('book').insert({
        title: 'Glasshouse',
        winner: '{"Prometheus"}',
        year: '2007',
        author_first: 'Charles',
        author_last: 'Stross',
        publisher: 'Ace Books',
      }),
      knex('book').insert({
        title: 'Learning The World',
        winner: '{"Prometheus"}',
        year: '2006',
        author_first: 'Ken',
        author_last: 'MacLeod',
        publisher: 'Orbit Books',
      }),
      knex('book').insert({
        title: 'Ancillary Sword',
        winner: '{"Locus"}',
        year: '2015',
        author_first: 'Ann',
        author_last: 'Leckie',
        publisher: 'Orbit Books',
      }),
      knex('book').insert({
        title: 'Abaddon\s Gate',
        winner: '{"Locus"}',
        year: '2014',
        author_first: 'James S. A.',
        author_last: 'Corey',
        publisher: 'Orbit Books',
      }),
      knex('book').insert({
        title: 'Embassytown',
        winner: '{"Locus"}',
        year: '2012',
        author_first: 'China',
        author_last: 'Mi'+String.fromCharCode(233)+'ville',
        publisher: 'Pan Macmillan',
      }),
      knex('book').insert({
        title: 'Boneshaker',
        winner: '{"Locus"}',
        year: '2010',
        author_first: 'Cherie',
        author_last: 'Priest',
        publisher: 'Tor Books',
      }),
      knex('book').insert({
        title: 'Anathem',
        winner: '{"Locus"}',
        year: '2009',
        author_first: 'Neal',
        author_last: 'Stephenson',
        publisher: 'William Morrow and Company',
      }),
      knex('book').insert({
        title: 'Accelerando',
        winner: '{"Locus"}',
        year: '2006',
        author_first: 'Charles',
        author_last: 'Stross',
        publisher: 'Ace Books',
      })




    ]);
  })
};
