
exports.seed = function(knex, Promise) {
  return knex('book').del().then(function(){
    return Promise.all([
      knex('book').insert({
        title: 'The Three-Body Problem',
        winner: '{"Hugo"}',
        year: '2015',
        author_first: 'Cixin',
        author_last: 'Liu',
        publisher: 'Tor Books',
      }),
      knex('book').insert({
        title: 'Ancillary Justice',
        winner: '{"Hugo", "Nebula"}',
        year: '2014',
        author_first: 'Ann',
        author_last: 'Leckie',
        publisher: 'Orbit Books',
      }),
      knex('book').insert({
        title: 'Redshirts',
        winner: '{"Hugo", "Locus"}',
        year: '2013',
        author_first: 'John',
        author_last: 'Scalzi',
        publisher: 'Tor Books',
      }),
      knex('book').insert({
        title: 'Among Others',
        winner: '{"Hugo", "Nebula"}',
        year: '2012',
        author_first: 'Jo',
        author_last: 'Walton',
        publisher: 'Tor Books',
      }),
      knex('book').insert({
        title: 'All Clear',
        winner: '{"Hugo", "Nebula", "Locus"}',
        year: '2011',
        author_first: 'Connie',
        author_last: 'Willis',
        publisher: 'Spectra Books',
      }),
      knex('book').insert({
        title: 'Blackout',
        winner: '{"Hugo", "Nebula", "Locus"}',
        year: '2011',
        author_first: 'Connie',
        author_last: 'Willis',
        publisher: 'Spectra Books',
      }),
      knex('book').insert({
        title: 'The Windup Girl',
        winner: '{"Hugo", "Nebula"}',
        year: '2010',
        author_first: 'Paolo',
        author_last: 'Bacigalupi',
        publisher: 'Night Shade Books',
      }),
      knex('book').insert({
        title: 'The City & The City',
        winner: '{"Hugo"}',
        year: '2010',
        author_first: 'China',
        author_last: 'Mi'+String.fromCharCode(233)+'ville',
        publisher: 'Del Rey Books',
      }),
      knex('book').insert({
        title: 'The Graveyard Book',
        winner: '{"Hugo"}',
        year: '2009',
        author_first: 'Neil',
        author_last: 'Gaiman',
        publisher: 'HarperCollins',
      }),
      knex('book').insert({
        title: 'The Yiddish Policemen\'s Union',
        winner: '{"Hugo", "Nebula", "Locus"}',
        year: '2008',
        author_first: 'Michael',
        author_last: 'Chabon',
        publisher: 'HarperCollins',
      }),
      knex('book').insert({
        title: 'Rainbows End',
        winner: '{"Hugo", "Locus"}',
        year: '2007',
        author_first: 'Vernor',
        author_last: 'Vinge',
        publisher: 'Tor Books',
      }),
      knex('book').insert({
        title: 'Spin',
        winner: '{"Hugo"}',
        year: '2006',
        author_first: 'Robert Charles',
        author_last: 'Wilson',
        publisher: 'Tor Books',
      }),
      knex('book').insert({
        title: 'Annihilation',
        winner: '{"Nebula"}',
        year: '2015',
        author_first: 'Jeff',
        author_last: 'VanderMeer',
        publisher: 'Farrar, Straus, and Giroux',
      }),
      knex('book').insert({
        title: '2312',
        winner: '{"Nebula"}',
        year: '2013',
        author_first: 'Kim Stanley',
        author_last: 'Robinson',
        publisher: 'Orbit Books',
      }),
      knex('book').insert({
        title: 'Powers',
        winner: '{"Nebula"}',
        year: '2009',
        author_first: 'Ursula K.',
        author_last: 'Le Guin',
        publisher: 'Harcourt',
      }),
      knex('book').insert({
        title: 'Seeker',
        winner: '{"Nebula"}',
        year: '2007',
        author_first: 'Jack',
        author_last: 'McDevitt',
        publisher: 'Ace Books',
      }),
      knex('book').insert({
        title: 'Camouflage',
        winner: '{"Nebula"}',
        year: '2006',
        author_first: 'Joe',
        author_last: 'Haldeman',
        publisher: 'Analog Science Fiction and Fact',
      }),
      knex('book').insert({
        title: 'Influx',
        winner: '{"Prometheus"}',
        year: '2015',
        author_first: 'Daniel',
        author_last: 'Suarez',
        publisher: 'Dutton',
      }),
      knex('book').insert({
        title: 'Nexus',
        winner: '{"Prometheus"}',
        year: '2014',
        author_first: 'Ramez',
        author_last: 'Naam',
        publisher: 'Angry Robot',
      }),
      knex('book').insert({
        title: 'Homeland',
        winner: '{"Prometheus"}',
        year: '2014',
        author_first: 'Cory',
        author_last: 'Doctorow',
        publisher: 'Tor Books',
      }),
      knex('book').insert({
        title: 'Pirate Cinema',
        winner: '{"Prometheus"}',
        year: '2013',
        author_first: 'Cory',
        author_last: 'Doctorow',
        publisher: 'Tor Books',
      }),
      knex('book').insert({
        title: 'The Freedom Maze',
        winner: '{"Prometheus"}',
        year: '2012',
        author_first: 'Delia',
        author_last: 'Sherman',
        publisher: 'Big Mouth House',
      }),
      knex('book').insert({
        title: 'Ready Player One',
        winner: '{"Prometheus"}',
        year: '2012',
        author_first: 'Ernest',
        author_last: 'Cline',
        publisher: 'Random House',
      }),
      knex('book').insert({
        title: 'Darkship Thieves',
        winner: '{"Prometheus"}',
        year: '2011',
        author_first: 'Sarah A.',
        author_last: 'Hoyt',
        publisher: 'Baen Books',
      }),
      knex('book').insert({
        title: 'The Unincorporated Man',
        winner: '{"Prometheus"}',
        year: '2010',
        author_first: 'Dani & Eytan',
        author_last: 'Kollin',
        publisher: 'Tor Books',
      }),
      knex('book').insert({
        title: 'Little Brother',
        winner: '{"Prometheus"}',
        year: '2009',
        author_first: 'Cory',
        author_last: 'Doctorow',
        publisher: 'Tor Books',
      }),
      knex('book').insert({
        title: 'Ha\'penny',
        winner: '{"Prometheus"}',
        year: '2008',
        author_first: 'Jo',
        author_last: 'Walton',
        publisher: 'Tor Books',
      }),

      knex('book').insert({
        title: 'The Gladiator',
        winner: '{"Prometheus"}',
        year: '2008',
        author_first: 'Harry',
        author_last: 'Turtledove',
        publisher: 'Tor Books',
      }),
      knex('book').insert({
        title: 'Glasshouse',
        winner: '{"Prometheus"}',
        year: '2007',
        author_first: 'Charles',
        author_last: 'Stross',
        publisher: 'Ace Books',
      }),
      knex('book').insert({
        title: 'Learning The World',
        winner: '{"Prometheus"}',
        year: '2006',
        author_first: 'Ken',
        author_last: 'MacLeod',
        publisher: 'Orbit Books',
      }),
      knex('book').insert({
        title: 'Ancillary Sword',
        winner: '{"Locus"}',
        year: '2015',
        author_first: 'Ann',
        author_last: 'Leckie',
        publisher: 'Orbit Books',
      }),
      knex('book').insert({
        title: 'Abaddon\s Gate',
        winner: '{"Locus"}',
        year: '2014',
        author_first: 'James S. A.',
        author_last: 'Corey',
        publisher: 'Orbit Books',
      }),
      knex('book').insert({
        title: 'Embassytown',
        winner: '{"Locus"}',
        year: '2012',
        author_first: 'China',
        author_last: 'Mi'+String.fromCharCode(233)+'ville',
        publisher: 'Pan Macmillan',
      }),
      knex('book').insert({
        title: 'Boneshaker',
        winner: '{"Locus"}',
        year: '2010',
        author_first: 'Cherie',
        author_last: 'Priest',
        publisher: 'Tor Books',
      }),
      knex('book').insert({
        title: 'Anathem',
        winner: '{"Locus"}',
        year: '2009',
        author_first: 'Neal',
        author_last: 'Stephenson',
        publisher: 'William Morrow and Company',
      }),
      knex('book').insert({
        title: 'Accelerando',
        winner: '{"Locus"}',
        year: '2006',
        author_first: 'Charles',
        author_last: 'Stross',
        publisher: 'Ace Books',
      }),
      knex('book').insert({
        title: 'The System of the World',
        winner: '{"Locus", "Prometheus"}',
        year: '2005',
        author_first: 'Neal',
        author_last: 'Stephenson',
        publisher: 'William Morrow',
      }),
      knex('book').insert({
        title: 'Ilium',
        winner: '{"Locus"}',
        year: '2004',
        author_first: 'Dan',
        author_last: 'Simmons',
        publisher: 'HarperCollins',
      }),
      knex('book').insert({
        title: 'The Years of Rice and Salt',
        winner: '{"Locus"}',
        year: '2003',
        author_first: 'Kim',
        author_last: 'Stanley',
        publisher: 'Bantam Books',
      }),
      knex('book').insert({
        title: 'Passage',
        winner: '{"Locus"}',
        year: '2002',
        author_first: 'Connie',
        author_last: 'Willis',
        publisher: 'Bantam Books',
      }),
      knex('book').insert({
        title: 'The Telling',
        winner: '{"Locus"}',
        year: '2001',
        author_first: 'Ursula K.',
        author_last: 'Le Guin',
        publisher: 'Harcourt',
      }),
      knex('book').insert({
        title: 'Cryptonomicon',
        winner: '{"Locus"}',
        year: '2000',
        author_first: 'Neal',
        author_last: 'Stephenson',
        publisher: 'Avon',
      }),
      knex('book').insert({
        title: 'To Say Nothing of the Dog',
        winner: '{"Locus", "Hugo"}',
        year: '1999',
        author_first: 'Connie',
        author_last: 'Willis',
        publisher: 'Bantam Spectra',
      }),
      knex('book').insert({
        title: 'The Rise of Endymion',
        winner: '{"Locus"}',
        year: '1998',
        author_first: 'Dan',
        author_last: 'Simmons',
        publisher: 'Bantam Books',
      }),
      knex('book').insert({
        title: 'Blue Mars',
        winner: '{"Locus", "Hugo"}',
        year: '1997',
        author_first: 'Kim Stanley',
        author_last: 'Robinson',
        publisher: 'Random House',
      }),
      knex('book').insert({
        title: 'The Diamond Age',
        winner: '{"Locus", "Hugo"}',
        year: '1996',
        author_first: 'Neal',
        author_last: 'Stephenson',
        publisher: 'Bantam Spectra',
      }),
      knex('book').insert({
        title: 'Mirror Dance',
        winner: '{"Locus", "Hugo"}',
        year: '1995',
        author_first: 'Lois McMaster',
        author_last: 'Bujold',
        publisher: 'Baen Books',
      }),
      knex('book').insert({
        title: 'Green Mars',
        winner: '{"Locus", "Hugo"}',
        year: '1994',
        author_first: 'Kim Stanley',
        author_last: 'Robinson',
        publisher: 'Bantam Dell',
      }),
      knex('book').insert({
        title: 'Doomsday Book',
        winner: '{"Locus", "Hugo", "Nebula"}',
        year: '1993',
        author_first: 'Connie',
        author_last: 'Willis',
        publisher: 'Bantam Spectra',
      }),
      knex('book').insert({
        title: 'Barrayar',
        winner: '{"Locus", "Hugo"}',
        year: '1992',
        author_first: 'Lois McMaster',
        author_last: 'Bujold',
        publisher: 'Baen Books',
      }),
      knex('book').insert({
        title: 'The Fall of Hyperion',
        winner: '{"Locus"}',
        year: '1991',
        author_first: 'Dan',
        author_last: 'Simmons',
        publisher: 'Doubleday',
      }),
      knex('book').insert({
        title: 'Hyperion',
        winner: '{"Locus", "Hugo"}',
        year: '1990',
        author_first: 'Dan',
        author_last: 'Simmons',
        publisher: 'Doubleday',
      }),
      knex('book').insert({
        title: 'Cyteen',
        winner: '{"Locus", "Hugo"}',
        year: '1989',
        author_first: 'C.J.',
        author_last: 'Cherryh',
        publisher: 'Warner Books',
      }),
      knex('book').insert({
        title: 'The Uplift War',
        winner: '{"Locus", "Hugo"}',
        year: '1988',
        author_first: 'David',
        author_last: 'Brin',
        publisher: 'Bantam Spectra',
      }),
      knex('book').insert({
        title: 'Speaker for the Dead',
        winner: '{"Locus", "Hugo", "Nebula"}',
        year: '1987',
        author_first: 'Orson Scott',
        author_last: 'Card',
        publisher: 'Tor Books',
      }),
      knex('book').insert({
        title: 'The Postman',
        winner: '{"Locus"}',
        year: '1986',
        author_first: 'David',
        author_last: 'Brin',
        publisher: 'Bantam Books',
      }),
      knex('book').insert({
        title: 'The Integral Trees',
        winner: '{"Locus"}',
        year: '1985',
        author_first: 'Larry',
        author_last: 'Niven',
        publisher: 'Del Rey Books',
      }),
      knex('book').insert({
        title: 'Startide Rising',
        winner: '{"Locus", "Hugo", "Nebula"}',
        year: '1984',
        author_first: 'David',
        author_last: 'Brin',
        publisher: 'Bantam Books',
      }),
      knex('book').insert({
        title: "Foundation's Edge",
        winner: '{"Locus", "Hugo"}',
        year: '1983',
        author_first: 'Isaac',
        author_last: 'Asimov',
        publisher: 'Doubleday',
      }),
      knex('book').insert({
        title: 'The Many Coloured Land',
        winner: '{"Locus"}',
        year: '1982',
        author_first: 'Julian',
        author_last: 'May',
        publisher: 'Tor Books',
      }),
      knex('book').insert({
        title: 'The Snow Queen',
        winner: '{"Locus", "Hugo"}',
        year: '1981',
        author_first: 'Joan D. ',
        author_last: 'Vinge',
        publisher: 'Dial Press',
      }),
      knex('book').insert({
        title: 'Titan',
        winner: '{"Locus"}',
        year: '1980',
        author_first: 'John',
        author_last: 'Varley',
        publisher: 'Berkley Books',
      }),
      knex('book').insert({
        title: 'Voyage from Yesteryear',
        winner: '{"Prometheus"}',
        year: '1983',
        author_first: 'James P.',
        author_last: 'Hogan',
        publisher: 'Del Rey Books',
      }),
      knex('book').insert({
        title: 'The Probability Broach',
        winner: '{"Prometheus"}',
        year: '1982',
        author_first: 'L. Neil',
        author_last: 'Smith',
        publisher: 'Del Rey Books',
      }),
      knex('book').insert({
        title: 'Wheels Within Wheels',
        winner: '{"Prometheus"}',
        year: '1979',
        author_first: 'F. Paul',
        author_last: 'Wilson',
        publisher: 'Doubleday',
      }),
      knex('book').insert({
        title: 'Downbelow Station',
        winner: '{"Hugo"}',
        year: '1982',
        author_first: 'C.J.',
        author_last: 'Cherryh',
        publisher: 'DAW Books',
      }),
      knex('book').insert({
        title: 'The Fountains of Paradise',
        winner: '{"Hugo", "Nebula"}',
        year: '1980',
        author_first: 'Arthur C.',
        author_last: 'Clarke',
        publisher: 'Victor Gollancz Ltd',
      }),
      knex('book').insert({
        title: 'Dreamsnake',
        winner: '{"Hugo", "Nebula"}',
        year: '1979',
        author_first: 'Vonda N.',
        author_last: 'McIntyre',
        publisher: 'Houghton Mifflin',
      }),
      knex('book').insert({
        title: 'No Enemy But Time',
        winner: '{"Nebula"}',
        year: '1983',
        author_first: 'Michael',
        author_last: 'Bishop',
        publisher: 'Timescape Books',
      }),
      knex('book').insert({
        title: 'The Claw of the Conciliator',
        winner: '{"Nebula"}',
        year: '1982',
        author_first: 'Gene',
        author_last: 'Wolfe',
        publisher: 'Timescape Books',
      }),
      knex('book').insert({
        title: 'Timescape',
        winner: '{"Nebula"}',
        year: '1981',
        author_first: 'Gregory',
        author_last: 'Benford',
        publisher: 'Simon & Schuster',
      }),
      knex('book').insert({
        title: 'Sims',
        winner: '{"Prometheus"}',
        year: '2004',
        author_first: 'F. Paul',
        author_last: 'Wilson',
        publisher: 'Tor Books',
      }),
      knex('book').insert({
        title: 'Night Watch',
        winner: '{"Prometheus"}',
        year: '2003',
        author_first: 'Terry',
        author_last: 'Pratchett',
        publisher: 'Doubleday',
      }),
      knex('book').insert({
        title: 'Psychohistorical Crisis',
        winner: '{"Prometheus"}',
        year: '2002',
        author_first: 'Donald',
        author_last: 'Kingsbury',
        publisher: 'Tor Books',
      }),
      knex('book').insert({
        title: 'The Forge of the Elders',
        winner: '{"Prometheus"}',
        year: '2001',
        author_first: 'L. Neil',
        author_last: 'Smith',
        publisher: 'Baen Books',
      }),
      knex('book').insert({
        title: 'A Deepness in the Sky',
        winner: '{"Prometheus", "Hugo"}',
        year: '2000',
        author_first: 'Vernor',
        author_last: 'Vinge',
        publisher: 'Tor Books',
      }),
      knex('book').insert({
        title: 'The Golden Globe',
        winner: '{"Prometheus"}',
        year: '1999',
        author_first: 'John',
        author_last: 'Varley',
        publisher: 'Ace Books',
      }),
      knex('book').insert({
        title: 'The Stone Canal',
        winner: '{"Prometheus"}',
        year: '1998',
        author_first: 'Ken',
        author_last: 'MacLeod',
        publisher: 'Legend Books',
      }),
      knex('book').insert({
        title: 'Kings of the High Frontier',
        winner: '{"Prometheus"}',
        year: '1997',
        author_first: 'Victor',
        author_last: 'Koman',
        publisher: 'Pulpless.com',
      }),
      knex('book').insert({
        title: 'The Star Fraction',
        winner: '{"Prometheus"}',
        year: '1996',
        author_first: 'Ken',
        author_last: 'MacLeod',
        publisher: 'Legend Books',
      }),
      knex('book').insert({
        title: 'The Stars Are Also Fire',
        winner: '{"Prometheus"}',
        year: '1995',
        author_first: 'Poul',
        author_last: 'Anderson',
        publisher: 'Tor Books',
      }),
      knex('book').insert({
        title: 'Pallas',
        winner: '{"Prometheus"}',
        year: '1994',
        author_first: 'L. Neil',
        author_last: 'Smith',
        publisher: 'Tor Books',
      }),
      knex('book').insert({
        title: 'The Multiplex Man',
        winner: '{"Prometheus"}',
        year: '1993',
        author_first: 'James P.',
        author_last: 'Hogan',
        publisher: 'Bantam Spectra',
      }),
      knex('book').insert({
        title: 'Fallen Angels',
        winner: '{"Prometheus"}',
        year: '1992',
        author_first: 'Larry',
        author_last: 'Niven',
        publisher: 'Baen Books',
      }),
      knex('book').insert({
        title: 'In the Country of the Blind',
        winner: '{"Prometheus"}',
        year: '1991',
        author_first: 'Michael F.',
        author_last: 'Flynn',
        publisher: 'Baen Books',
      }),
      knex('book').insert({
        title: "Solomon's Knife",
        winner: '{"Prometheus"}',
        year: '1990',
        author_first: 'Victor',
        author_last: 'Koman',
        publisher: 'Franklin Watts',
      }),
      knex('book').insert({
        title: 'Moon of Ice',
        winner: '{"Prometheus"}',
        year: '1989',
        author_first: 'Bran',
        author_last: 'Linaweaver',
        publisher: 'Arbor House',
      }),
      knex('book').insert({
        title: 'The Jehovah Contract',
        winner: '{"Prometheus"}',
        year: '1988',
        author_first: 'Victor',
        author_last: 'Koman',
        publisher: 'Franklin Watts',
      }),
      knex('book').insert({
        title: 'Marooned in Realtime',
        winner: '{"Prometheus"}',
        year: '1987',
        author_first: 'Vernor',
        author_last: 'Vinge',
        publisher: 'Analog Science Fiction and Fact',
      }),
      knex('book').insert({
        title: 'The Cybernetic Samurai',
        winner: '{"Prometheus"}',
        year: '1986',
        author_first: 'Victor',
        author_last: 'Mil'+String.fromCharCode(225)+'n',
        publisher: 'Arbor House',
      }),
      knex('book').insert({
        title: 'The Rainbow Cadenza',
        winner: '{"Prometheus"}',
        year: '1984',
        author_first: 'J. Neil',
        author_last: 'Schulman',
        publisher: 'Simon & Schuster',
      }),
      knex('book').insert({
        title: 'Jonathan Strange & Mr Norrell',
        winner: '{"Hugo"}',
        year: '2005',
        author_first: 'Susanna',
        author_last: 'Clarke',
        publisher: 'Bloomsbury Publishing',
      }),
      knex('book').insert({
        title: 'Paladin of Souls',
        winner: '{"Hugo", "Nebula"}',
        year: '2004',
        author_first: 'Lois McMaster',
        author_last: 'Bujold',
        publisher: 'Eos',
      }),
      knex('book').insert({
        title: 'Hominids',
        winner: '{"Hugo"}',
        year: '2003',
        author_first: 'Robert J.',
        author_last: 'Sawyer',
        publisher: 'Analog Science Fiction and Fact',
      }),
      knex('book').insert({
        title: 'American Gods',
        winner: '{"Hugo", "Nebula"}',
        year: '2002',
        author_first: 'Neil',
        author_last: 'Gaiman',
        publisher: 'William Morrow and Company',
      }),
      knex('book').insert({
        title: 'Harry Potter and the Goblet of Fire',
        winner: '{"Hugo"}',
        year: '2001',
        author_first: 'J.K.',
        author_last: 'Rowling',
        publisher: 'Bloomsbury Publishing',
      }),
      knex('book').insert({
        title: 'Forever Peace',
        winner: '{"Hugo", "Nebula"}',
        year: '1998',
        author_first: 'Joe',
        author_last: 'Haldeman',
        publisher: 'Ace Books',
      }),
      knex('book').insert({
        title: 'A Fire Upon the Deep',
        winner: '{"Hugo"}',
        year: '1993',
        author_first: 'Vernor',
        author_last: 'Vinge',
        publisher: 'Tor Books',
      }),
      knex('book').insert({
        title: 'The Vor Game',
        winner: '{"Hugo"}',
        year: '1991',
        author_first: 'Lois McMaster',
        author_last: 'Bujold',
        publisher: 'Baen Books',
      }),
      knex('book').insert({
        title: "Ender's Game",
        winner: '{"Hugo", "Nebula"}',
        year: '1986',
        author_first: 'Orson Scott',
        author_last: 'Card',
        publisher: 'Tor Books',
      }),
      knex('book').insert({
        title: 'Neuromancer',
        winner: '{"Hugo", "Nebula"}',
        year: '1985',
        author_first: 'William',
        author_last: 'Gibson',
        publisher: 'Ace Books',
      }),
      knex('book').insert({
        title: 'The Speed of Dark',
        winner: '{"Nebula"}',
        year: '2004',
        author_first: 'Elizabeth',
        author_last: 'Moon',
        publisher: 'Balantine Books',
      }),
      knex('book').insert({
        title: 'The Quantum Rose',
        winner: '{"Nebula"}',
        year: '2002',
        author_first: 'Catherine',
        author_last: 'Asaro',
        publisher: 'Tor Books',
      }),
      knex('book').insert({
        title: "Darwin's Radio",
        winner: '{"Nebula"}',
        year: '2001',
        author_first: 'Greg',
        author_last: 'Bear',
        publisher: 'Del Rey Books',
      }),
      knex('book').insert({
        title: 'Parable of the Talents',
        winner: '{"Nebula"}',
        year: '2000',
        author_first: 'Octavia E.',
        author_last: 'Butler',
        publisher: 'Seven Stories Press',
      }),
      knex('book').insert({
        title: 'The Moon and the Sun',
        winner: '{"Nebula"}',
        year: '1998',
        author_first: 'Vonda N.',
        author_last: 'McIntyre',
        publisher: 'Pocket Books',
      }),
      knex('book').insert({
        title: 'Slow River',
        winner: '{"Nebula"}',
        year: '1997',
        author_first: 'Nicola',
        author_last: 'Griffith',
        publisher: 'Del Rey Books',
      }),
      knex('book').insert({
        title: 'The Terminal Experiment',
        winner: '{"Nebula"}',
        year: '1996',
        author_first: 'Robert J.',
        author_last: 'Sawyer',
        publisher: 'HarperPrism',
      }),
      knex('book').insert({
        title: 'Moving Mars',
        winner: '{"Nebula"}',
        year: '1995',
        author_first: 'Greg',
        author_last: 'Bear',
        publisher: 'Tor Books',
      }),
      knex('book').insert({
        title: 'Red Mars',
        winner: '{"Nebula"}',
        year: '1994',
        author_first: 'Kim Stanley',
        author_last: 'Robinson',
        publisher: 'Bantam Spectra',
      }),
      knex('book').insert({
        title: 'Stations of the Tide',
        winner: '{"Nebula"}',
        year: '1992',
        author_first: 'Michael',
        author_last: 'Swanwick',
        publisher: "Asimov's Science Fiction",
      }),
      knex('book').insert({
        title: 'Tehanu: The Last Book of Earthsea',
        winner: '{"Nebula"}',
        year: '1991',
        author_first: 'Ursula K.',
        author_last: 'Le Guin',
        publisher: 'Macmillan Publishers',
      }),
      knex('book').insert({
        title: "The Healer's War",
        winner: '{"Nebula"}',
        year: '1990',
        author_first: 'Elizabeth Ann',
        author_last: 'Scarborough',
        publisher: 'Doubleday Foundation',
      }),
      knex('book').insert({
        title: 'Falling Free',
        winner: '{"Nebula"}',
        year: '1989',
        author_first: 'Lois McMaster',
        author_last: 'Bujold',
        publisher: 'Analog Science Fact & Fiction',
      }),
      knex('book').insert({
        title: 'The Falling Woman',
        winner: '{"Nebula"}',
        year: '1988',
        author_first: 'Pat',
        author_last: 'Murphy',
        publisher: 'Tor Books',
      }),
    ]);
  })
};
